{% set name = "xsarslc" %}
{% set version = "2023.11.17.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xsarslc-{{ version }}.tar.gz
  sha256: 5854ca141d681291c9ba728e4c6e811dd58698a216f02ec85003a4d3597e2c59

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=64.0
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - xarray
    - numpy
    - netcdf4
    - shapely
    - xrft
    - xarray-datatree
    - importlib-resources
    - tqdm

test:
  imports:
    - xsarslc
  commands:
    - pip check
  requires:
    - pip

about:
  summary: Python library to compute cross spectra from SAR image
  license: GPL-3.0-or-later
  license_file: LICENSE
  home: https://github.com/umr-lops/xsar_slc

extra:
  recipe-maintainers:
    - agrouaze
    - lanougue
    - keewis
